<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="ctm.xsl" type="text/xsl"?>

<!DOCTYPE ctm [
<!ELEMENT ctm (information*)>
<!ELEMENT information (id, name, lname , teyu, tal)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT teyu (#PCDATA)>
<!ELEMENT tal (#PCDATA)>
]>

<ctm>

    <information>
        <id> MB01 </id>
        <name> นาย ฉัตรชัย </name>
        <lname> ถาวร </lname>
        <teyu> 4/55 กทม </teyu>
        <tal> 0988546664 </tal>
    </information>

    <information>
        <id> MB02 </id>
        <name> นาย เตง </name>
        <lname> เป็นฝี </lname>
        <teyu> 2/5 กทม </teyu>
        <tal> 0879547575 </tal>
    </information>

    <information>
        <id> MB03 </id>
        <name> นาย ซี </name>
        <lname> สุภสร </lname>
        <teyu> 6/53 กทม </teyu>
        <tal> 0985657689 </tal>
    </information>

    <information>
        <id> MB04 </id>
        <name> นาย ดี </name>
        <lname> ทุกด้าน </lname>
        <teyu> 7/95 กทม </teyu>
        <tal> 0989564678 </tal>
    </information>

    <information>
        <id> MB05 </id>
        <name> นาย น้อย </name>
        <lname> คนนคร </lname>
        <teyu> 4/52 กทม </teyu>
        <tal> 0958764568 </tal>
</information>

</ctm>